apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kota-pokedex-api-data
  labels:
    app: kota-pokedex-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
