apiVersion: v1
kind: Service
metadata:
  name: kota-pokedex-web
  labels:
    app: kota-pokedex-web
spec:
  type: ClusterIP
  selector:
    app: kota-pokedex-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
